### PR TITLE
Landing page UI

### LINKED ISSUE #6: Landing Page
- Navbar
- Footer
- Landing page acc to Figma

### PR DESCRIPTION
**Pull request by harshjohar**
Resolves #6 

- Responsive UI of Landing Page
- Fixed Header and Footer components

### CODE REVIEW

**Comment by harasees-singh** [comment]
image
this is not looking great.

**Comment by harasees-singh** [comment]
'Learn More' animation can be shortened

**Comment by harshjohar** [comment]
> image this is not looking great.

Yeah, a banner will come above it to enhance the whole thing, that is part of #5. Everything is in accordance with figma.

**Review by Ishwarendra — COMMENTED** [review]
lgtm

**Review by Ishwarendra — APPROVED** [review]
lgtm

**Pull request merged**
