### PR TITLE
Create Event UI added

### PR DESCRIPTION
**Pull request by iamakashrout**

### CODE REVIEW

**Review by harshjohar — CHANGES_REQUESTED** [review]
Build is failing.

Check the logs of `yarn build` for information. Issue is related to calling of react hooks in a conditional manner in `/pages/events.tsx`

**Review by harshjohar — APPROVED** [review]
LGTM

**Comment by harshjohar** [comment]
btw, part of this issue was to stitch with backend but :crycatok:

**Comment by iamakashrout** [comment]
will add it next

**Pull request merged**
